### PR TITLE
Remove FrozenAsset's need to implement the Asset interface

### PR DESCRIPTION
**Pull request by justinedelson**

### CODE REVIEW

**Comment by badvision** [comment]
I think Run D.M.C. wrote a song about this....  I'm adding some temporary logging so I can figure out what methods are actually used.  It goes through the product API so I don't actually know directly.

**Comment by justinedelson** [comment]
You should be able to add a log statement to the invocation handler. poor man's AOP

**Comment by badvision** [comment]
I like it.  Actually as much as I've hacked about with reflection I've never used an Invocation handler.  What is this sorcery??!?  😄

**Comment by justinedelson** [comment]
https://docs.oracle.com/javase/7/docs/api/java/lang/reflect/Proxy.html... since 1.3 :)

**Comment by badvision** [comment]
Yeah I know that I just didn't know you could pass it as another object and not have class cast exceptions.  Seems to be the exception to every case I ever knew. :D

**Pull request merged**
